### ISSUE TITLE
Monitor issue

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/addon-lxcone#11]
Hi,

I'm trying to make this work and found a monitor issue that seems to be why I can't get the host to "ON" state.
First, I'm on Debian8 on ARM64.

This is from my oned.log

```
Thu Oct 27 01:25:04 2016 [Z0][InM][D]: Monitoring host 127.0.0.1 (0)
Thu Oct 27 01:25:04 2016 [Z0][AuM][D]: Message received: AUTHENTICATE SUCCESS 13 -

Thu Oct 27 01:25:04 2016 [Z0][ReM][D]: Req:3280 UID:0 HostPoolInfo invoked 
Thu Oct 27 01:25:04 2016 [Z0][ReM][D]: Req:3280 UID:0 HostPoolInfo result SUCCESS, "<HOST_POOL><HOST><ID..."
Thu Oct 27 01:25:06 2016 [Z0][ONE][E]: Error parsing host information: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at lin
e 35, columns 512:513. Monitoring information: 
ARCH=aarch64
MODELNAME="HYPERVISOR=lxc
TOTALCPU=400
CPUSPEED=0
TOTALMEMORY=1760508
USEDMEMORY=368840
FREEMEMORY=1391668
FREECPU=400
USEDCPU=0
NETRX=58324808
NETTX=2156662
DS_LOCATION_USED_MB=6423
DS_LOCATION_TOTAL_MB=14784
DS_LOCATION_FREE_MB=8182
DS = [
  ID = 0,
  USED_MB = 6423,
  TOTAL_MB = 14784,
  FREE_MB = 8182
]
DS = [
  ID = 1,
  USED_MB = 6423,
  TOTAL_MB = 14784,
  FREE_MB = 8182
]
DS = [
  ID = 2,
  USED_MB = 6423,
  TOTAL_MB = 14784,
  FREE_MB = 8182
]
HOSTNAME=odroidc2
VM_POLL=YES
VERSION="5.2.0"

Thu Oct 27 01:25
```

Do you see why it has an issue?
At the moment I don't see the problem :(

**Comment by FlorianHeigl** [comment]
Actually, one second look:

```
ARCH=aarch64
MODELNAME="HYPERVISOR=lxc
TOTALCPU=400
```
That seems like the MODELNAME is opening a quote which never closes?

**Comment by FlorianHeigl** [comment]
The quote handling in parsing the CPU info is really horrible. I see you just copied that from the KVM sources, so don't feel too blamed.

```
    echo -n "MODELNAME=\""
    grep -m 1 "model name" /proc/cpuinfo | cut -d: -f2 | sed -e 's/^ *//' | sed -e 's/$/"/'
```

How this works is the first quote comes from echo number one. The second line is from the sed, which will ONLY work if the whole grepping was OK.
This is kind of dailywtf material.

Accordingly, when it's not a x86 arch, instead of just turning no CPU type everything is mis-parsed.
Which is why this turns into such a huge bug.

I'm making some patch for it.

**Comment by sergiojvg** [comment]
Hi
You are right, we missed that, this driver was never intended for ARM so never saw this coming. 
Right now we left support for this driver because we are working on an lxd driver that will fix that and many other issues. It will also add support for more features while presenting a cleaner code. 
Are you working with a Raspberry Pi3 or a Pine64? That's one of the main goals we have with this new driver but not being able to buy this mini computers in Cuba is really slowing us down.
If you want you can leave me your email or write me to sergiojvg92@gmail.com and I'll keep you up to date with the new driver, we should begin testing it on our data center in 2 or 3 weeks.
Bests

**Comment by FlorianHeigl** [comment]
Sorry for long time no answer here, I'm working with Odroid C2.

**Comment by FlorianHeigl** [comment]
Could you look at & merge the patch?
